title = "Michael Mommert"
baseURL = "https://mommermi.github.io"
languageCode = "en-us"
theme = ["ananke"]
#resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 100 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Michael Mommert"
    weight = 0.5
    contentDir = "content/de"
  [languages.en]
    title = "Michael Mommert"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "Michael Mommert: AI for Remote Sensing"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  body_classes = "avenir bg-nearwhite"
  # cover_dimming_class: overlay for banner images 
  cover_dimming_class = "bg-black-40"
  background_color_class = "bg-black-60"
  recent_posts_number = 3
  show_reading_time = true
  custom_css = ["css/override.css"]
  
# required to use inline html
[markup.goldmark.renderer]
 unsafe = true